typography_spectrum: 0.21080767922103405
color:
  brandStrength: 0.8904215998481959
  lightness: 0.17511461907997727
  saturation: 0.47581068286672235
  rhythmicContrast: 0.7142537934705615
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.5936873147729784
author:
  name: Charlotte Wrinch
  email: charlottewrinch@gmail.com
  url: 'http://charlottewrinch.com'
name: Charlotte Wrinch
title: Charlotte Wrinch
description: Singer-Songwriter
